[build]
  publish = "."

[[redirects]]
  from = "/book"
  to = "https://nv.doronichev.com"
  status = 301
  force = true

[[redirects]]
  from = "/book.html"
  to = "https://nv.doronichev.com"
  status = 301
  force = true
